### ISSUE TITLE
The pen thickness is much thicker than the website, and squiggly

### ISSUE THREAD

**Issue by archydeberker** [koaning/drawdata#2]
![image](https://user-images.githubusercontent.com/9258253/114203141-bd542e00-990c-11eb-921e-ae3a4af106e3.png)

Very mysteriously, I get a thick pen line and lots of involuntary squiggles when drawing in the iFrame. This doesn't happen on `drawdata.xyz`

**Comment by koaning** [comment]
The drawdata website has three charts to draw, this library (which is very much work in progress) only has the scatter one, which is supposed to be very jiggily.

**Comment by archydeberker** [comment]
Sorry, that was incredibly dense of me! I had only tried the line and histogram versions on `drawdata.xyz`!
