### ISSUE TITLE
Can the JavaScript code that's used on the website be included in this repo as well?

### ISSUE THREAD

**Issue by Arpanio** [koaning/drawdata#4]
I see that this repository only has the Python wrappers to the JS code. Can the JS code be included here as well?

**Comment by koaning** [comment]
It's currently linking to HTML yes. I was thinking of maybe running it as a local template but I didn't have the time to get around to that yet.

**Comment by koaning** [comment]
I've tried pointing to the HTML locally with Iframes but then there needs to be a server properly hosting them.

**Comment by Arpanio** [comment]
Solving that will be necessary for the python repo to make sense... That's true.

Is there a separate repo for the JS code? I want to play around with this, so I am primarily interested in the JS code to be honest.

**Comment by Arpanio** [comment]
> I've tried pointing to the HTML locally with Iframes but then there needs to be a server properly hosting them, which doesn't really play nice with jupyter security settings.

Would it make sense to have a bash script included with the module, which can be run from the Jupyter notebook using ! (to call the bash process)?

**Comment by koaning** [comment]
If you follow the url you'll see the js code hosted next to the html.

**Comment by falcaopetri** [comment]
It would be really nice if we could fork or even contribute to the JS code.
I don't have experience in developing for Jupyter, but what about making drawdata a Jupyter Extension? Wouldn't that allow executing the required JS?

And thanks for this work @koaning, it's a great teaching resource.

**Comment by koaning** [comment]
I'm open to making it an extension, but it'd be preferable if it would also run with users needing to install ipywidgets. I tried running it with python's `Template` class but that wouldn't work without hosting an iframe. 

I'm certainly open to ideas here, the current implementation is indeed a quick hack to see if folks were interested. Looking at the [stats](https://pepy.tech/project/drawdata) there's some interest, but it's not *that* much.

**Comment by koaning** [comment]
There's a new anywidget method that we'll use going forward instead. Should fix this issue!
