### ISSUE TITLE
There is a problem when I wanna copy from clipboard

### ISSUE THREAD

**Issue by moisesStevend** [koaning/drawdata#6]
This error appears when I use this command:

`pd.read_clipboard(sep=",")`

ParserError: Error tokenizing data. C error: EOF inside string starting at row 0

![image](https://user-images.githubusercontent.com/19917865/231241705-7ab5fb86-b43c-4db8-8bcb-cc441a51eef2.png)

The entire error is this:

![image](https://user-images.githubusercontent.com/19917865/231242019-107d54a4-62a7-4f7b-b209-ebbcb276a12b.png)

​

**Comment by koaning** [comment]
That seems to be an issue with pandas. What version are you using? It might be worth downgrading because pandas is going to be going v2 around this time and you may be dealing with an alpha version.
